env:
  - GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
  -
    main: ./client/cmd/bitwrk-client/
    binary: bitwrk-client
    ldflags: -s -w -X main.ClientVersion={{ .Major }}.{{ .Minor }}.{{ .Patch }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
#      - arm64
#      - 386
#      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
sign:
  artifacts: checksum
archives:
  -
    format_overrides:
      - goos: windows
        format: zip

    replacements:
      darwin: osx
      linux: linux
      windows: windows
      386: x86
      amd64: x64

    files:
      - resources/**/*

    wrap_in_directory: "{{ .ProjectName }}-{{ .Version }}"

    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}.{{ .Arch }}"
checksum:
  name_template: 'checksums-{{ .Version }}.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
