language: go

go:
 - 1.11

install:
 - echo "Luckily, there are no dependencies"

script:
 - export GOPATH=$(pwd):$GOPATH
 - go test bitbucket.org/ww/goautoneg github.com/indyjo/bitwrk-client/...
 - go install ./src/github.com/indyjo/bitwrk-client/cmd/bitwrk-client/ && bin/bitwrk-client --help || [ $? -eq 2 ]

