language: go

os:
  - linux
  - osx

go:
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  global:
    GO111MODULE=on

script:
  - go test ./...
  - go build ./...
  - go build ./client/cmd/bitwrk-client/
  - go build ./server/appengine/
  - ./bitwrk-client --help || [ $? -eq 2 ]
