runtime: go111

automatic_scaling:
  max_concurrent_requests: 200

main: server/appengine
  
handlers:
- url: /js
  static_dir: static/js
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: static/favicon.ico
  
- url: /.*
  script: auto
